version: '3.7'
# Removed subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1
# I had this:
# cat ~/.docker/config.json
# {"auths":{},"credsStore":"", "credsStore":"desktop","stackOrchestrator":"swarm"}
# I updated to this:
# {"auths":{},"credsStore":"","stackOrchestrator":"swarm"}
services:
  user-service:
    image: ishugarg34/user-service:tag1
    #build:
      #context: .
      #dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: # Start the depends_on first
      - mysql 
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: todos
      RDS_USERNAME: root
      RDS_PASSWORD: root

  mysql:
    image: ishugarg34/mysql-image:tag1
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_HOST: root
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: User_detail
    volumes:
      - mysql-database-data-volume:/var/lib/mysql

# Volumes
volumes:
  mysql-database-data-volume: